server:
    port: 8080

spring:
  datasource:
    username: feipengda
    password: feipengda123
    url: jdbc:mysql://119.96.241.151:3306/ezmzj?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent-output : true
  mvc:
      throw-exception-if-no-handler-found: true  #开启异常捕捉
  resources:
      add-mappings: false #开启异常捕捉

logging:
  level:
     cn.bld.enterprise.modules.sys.dao : debug


